// flow-typed signature: 49213f9711cf5f87ac263a2bae1fda76
// flow-typed version: <<STUB>>/expobook_v^0.0.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expobook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expobook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expobook/__expobook__/components/component-list' {
  declare module.exports: any;
}

declare module 'expobook/__expobook__/components/row-item' {
  declare module.exports: any;
}

declare module 'expobook/__expobook__/components/state-restore' {
  declare module.exports: any;
}

declare module 'expobook/__expobook__/components/state-sync' {
  declare module.exports: any;
}

declare module 'expobook/__expobook__/entry' {
  declare module.exports: any;
}

declare module 'expobook/__expobook__/index' {
  declare module.exports: any;
}

declare module 'expobook/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expobook/__expobook__/components/component-list.js' {
  declare module.exports: $Exports<'expobook/__expobook__/components/component-list'>;
}
declare module 'expobook/__expobook__/components/row-item.js' {
  declare module.exports: $Exports<'expobook/__expobook__/components/row-item'>;
}
declare module 'expobook/__expobook__/components/state-restore.js' {
  declare module.exports: $Exports<'expobook/__expobook__/components/state-restore'>;
}
declare module 'expobook/__expobook__/components/state-sync.js' {
  declare module.exports: $Exports<'expobook/__expobook__/components/state-sync'>;
}
declare module 'expobook/__expobook__/entry.js' {
  declare module.exports: $Exports<'expobook/__expobook__/entry'>;
}
declare module 'expobook/__expobook__/index.js' {
  declare module.exports: $Exports<'expobook/__expobook__/index'>;
}
declare module 'expobook/cli.js' {
  declare module.exports: $Exports<'expobook/cli'>;
}
declare module 'expobook/index' {
  declare module.exports: $Exports<'expobook'>;
}
declare module 'expobook/index.js' {
  declare module.exports: $Exports<'expobook'>;
}
